# Generated by Django 2.0 on 2018-01-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Client'),
        ),
    ]
